### ISSUE TITLE
Client: QR Mint

### ISSUE THREAD

**Issue by developerasun** [asunlabs/pawcon-monorepo#112]
## Sub-tasks

- [ ] Should create a QR code per NFT
- [ ] Should redirect user to NFT detail page
- [ ] Should use qrcodejs: https://github.com/davidshimjs/qrcodejs
