### ISSUE TITLE
Server: Go configs

### ISSUE THREAD

**Issue by developerasun** [asunlabs/pawcon-monorepo#126]
## Sub-tasks

- [ ] Fiber: hot reload
- [ ] Golines: auto code formatting
- [ ] Color: colorful logging in terminal
- [ ] Godotenv: configure .env
