### ISSUE TITLE
Blockchain: Governance/DAO

### ISSUE THREAD

**Issue by developerasun** [asunlabs/pawcon-monorepo#138]
## Sub-tasks

- [ ] Should analyze core contracts for DAO
- [ ] Should set DAO conditions: voting delay, voting period, voting token, timelock, quorum
- [ ] Should set a governor
- [ ] Should set a timelock
- [ ] Should set a governance token
- [ ] should set an agenda
