### ISSUE TITLE
Server: implement ERD

### ISSUE THREAD

**Issue by developerasun** [asunlabs/pawcon-monorepo#142]
## Sub-tasks

- [ ] Should implement ERD schema
- [ ] Should set a PK and FK between tables
- [ ] Should migrate the schema to database
