### ISSUE TITLE
Server: API test prototype

### ISSUE THREAD

**Issue by developerasun** [asunlabs/pawcon-monorepo#148]
## Sub-tasks

- [x] Should add Fiber test cases for API handlers
- [x] Should integrate DB operation for the test cases
- [x] Should add basic error handling functions
