### ISSUE TITLE
Blockchain: UUPS ERC777 Catnip

### ISSUE THREAD

**Issue by developerasun** [asunlabs/pawcon-monorepo#23]
## Sub-tasks

- [x] Should be UUPS-upgradeable
- [x] Should have a max supply: 10 billion
- [x] Should mint a catnip token
- [x] Token receivability, withdrawability with ERC1820
- [x] Should stake with token timelock: 1 year only
- [x] Should set a limited-time whitelist: 1 week
