### ISSUE TITLE
Docs: HUGO static website

### ISSUE THREAD

**Issue by developerasun** [asunlabs/pawcon-monorepo#34]
## Sub-tasks 

- [x] HUGO adoption for creating a static website
- [x] Netlify adoption for static website deployment
- [x] Netlify continuous delivery: linking git repo
- [x] Netlify hook api key and add to github secrets
- [x] Navigation menu

**workflows**
hugo (static build command) => netlify deploy => static website updated
