### ISSUE TITLE
Actions: issue and docs automation

### ISSUE THREAD

**Issue by developerasun** [asunlabs/pawcon-monorepo#36]
## Sub-tasks

- [ ] feature branch: enhancement, test
- [ ] agile backlog: project draft converted to issue 
- [ ] pawcon docs: turborepo apps documentation uploaded to a HUGO static website

## Research 

project
project_card
project_column
