### ISSUE TITLE
Client: Base wireframe

### ISSUE THREAD

**Issue by developerasun** [asunlabs/pawcon-monorepo#37]
## Sub-tasks 

- [x] Find wireframe example
- [x] Find wireframe solutions: uizard
- [x] Set AsunMint web wireframe
- [x] Set AsunSwap web wireframe
