### ISSUE TITLE
Blockchain: UUPS ERC721 CuriousPawoneer

### ISSUE THREAD

**Issue by developerasun** [asunlabs/pawcon-monorepo#43]
## Sub-tasks

- [ ] Auction NFT
- [ ] Swap NFT
- [ ] Staking with timelock, 1 year only
- [ ] Oracle: Dynamic token price with datafeeds, proportional to current ETH price
- [ ] Oracle: Random token rarity with vrf
- [ ] Receive and withdraw NFT 
- [ ] Auto id with Counter
- [ ] Access control(minter, burner, pauser)
- [ ] Base64 on-chain NFT media management
- [ ] Limited-time whitelist
- [ ] NFT Airdrop
