### ISSUE TITLE
Doc: move discussion to docs web

### ISSUE THREAD

**Issue by developerasun** [asunlabs/pawcon-monorepo#55]
## Sub-tasks 

- [x] add self-promotion video in index page
- [x] client discussion to docs-pawcon
- [x] server discussion to docs-pawcon
