### ISSUE TITLE
Blockchain: Utility NFT Auction

### ISSUE THREAD

**Issue by developerasun** [asunlabs/pawcon-monorepo#58]
## Sub-task

- [x] NFT bid for 7 days with timelock
- [x] Hold bidder's Ether in contract
- [x] Set bid winner
- [x] Transfer NFT to bid winner
