### ISSUE TITLE
Client: Mint page

### ISSUE THREAD

**Issue by developerasun** [asunlabs/pawcon-monorepo#60]
## Sub-tasks

**simple and quick**

- [x] Base wireframe
- [x] AsunMint prototype UI
- [x] State mgmt: Context hook adoption
- [x] Connect wallet: Web3Modal(Metamask, Coinbase) 
- [x] Render NFT asset images: prototype => Docker server API
- [x] Render infinite scroll for NFT gallery: prototype =>  Docker server API
- [x] Render Bid history
