### ISSUE TITLE
Client: code migration

### ISSUE THREAD

**Issue by developerasun** [asunlabs/pawcon-monorepo#64]
## Sub-tasks

- [x] landing page 1 : welcome visitor
- [x] landing page 2 : meowrun
- [x] pawcon ver 0.2.0 React code migration: navigation, footer, button, card
- [x] metadata tags
