### ISSUE TITLE
Blockchain: Utility Pair Pool

### ISSUE THREAD

**Issue by developerasun** [asunlabs/pawcon-monorepo#67]
## Sub-tasks 

**Yield farming**

### Pair pool

- [ ] Pair liquidity pool 1: (Ether, Catnip) <=> (Ether, ERC777)
- [ ] Pair liquidity pool 2: (Ether, USDC) <=> (Ether, ERC20)
- [ ] Pair liquidity pool 3: (Ether, DAI) <=> (Ether, ERC20)
