### ISSUE TITLE
Authentication: Sign in methods

### ISSUE THREAD

**Issue by developerasun** [asunlabs/pawcon-monorepo#68]
## Sub-tasks

- [ ] Blockchain: Sign in with Ethereum
- [ ] Backend: Sign in with json web token
- [ ] Backend: Sign in wiwth OAuth
