### ISSUE TITLE
Client: IPFS deployment

### ISSUE THREAD

**Issue by developerasun** [asunlabs/pawcon-monorepo#75]
## Sub-task 

- [ ] token metadata setup
- [ ] IPFS website deployment
- [ ] Netlify & Github Actions continuous delivery
