### ISSUE TITLE
Server: API

### ISSUE THREAD

**Issue by developerasun** [asunlabs/pawcon-monorepo#82]
## Sub-tasks

- [ ] Should upload NFT media to IPFS service: Pinata cloud or NFT.storage
- [ ] Should use Go Fiber framework
- [ ] Should serve NFT media asset to client
- [ ] Should dockerize server API
- [ ] Should upload the dockerized app to DockerHub
- [ ] Should upload API documentation to docs website
