### ISSUE TITLE
Server: API server prototype

### ISSUE THREAD

**Issue by developerasun** [asunlabs/pawcon-monorepo#86]
## Sub-tasks

- [x] Go web server framework selection: Fiber, GORM, Sqlite3
- [x] Go server hot reloading: Fiber CLI
- [x] Should dockerize server app
- [x] Integrate Opensea metadata standard
- [x] Docker server: CORS
