### ISSUE TITLE
Server: Auth

### ISSUE THREAD

**Issue by developerasun** [asunlabs/pawcon-monorepo#87]
## Sub-tasks

- [ ] Go json web token authentication
- [ ] Go google Oauth authentication
- [ ] NFT of the month voting access control
- [ ] NFT mint whitelist request enroll access control
